# -*- coding: utf-8 -*-
"""firefly_not_done.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lH9f2BM7kNc59lCUU60j1qlf2iDlp1Pk
"""



from sklearn import svm
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score
from numpy.random import default_rng
import numpy as np
from sklearn.model_selection import train_test_split
import random
import math

data = load_digits()

n_samples = len(data.images)
X = data.images.reshape((n_samples, -1))
Y = data['target']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, shuffle= True, random_state= 42)

# modle implementation
def fitness_function(x):  
	# x[0] = C and x[1] = gamma
	clf = svm.SVC(kernel='rbf', C=x[0], gamma=x[1], random_state=42)
	scores = cross_val_score(clf, X, Y, cv=5)
	
	return scores.mean()

from numpy.random import rand

import numpy as np
import matplotlib.pyplot as plt

from time import perf_counter, process_time
import imageio
import os

class BaseSearchAlgorithm():
    
    def __init__(self, name, **kwargs):
        print(name, kwargs)
        self.name = name
        self.objective = None
        self.objective_fct = None

        self.solutions = []
        self.history = []
        self.best_solution = None
        self.params = kwargs

        self.n = self.params['n'] # size of population
        self.d = self.params['d'] # dimensionality of solution space
        
        self.range_min = self.params['range_min'] # lower bound in all dimensions
        self.range_max = self.params['range_max'] # upper bound in all dimensions
        
        if np.isscalar(self.range_min):
            self.range_min = np.repeat(self.range_min, self.d)
            
        if np.isscalar(self.range_max):
            self.range_max = np.repeat(self.range_max, self.d)
            
        self.evaluation_count = 0
            
        
    def constraints_satisfied(self):
        return True
    

    def get_best_solution(self, key=None):
        if not key:
            key = self.objective_fct
        
        if self.objective == 'min':
            candidate = min(self.solutions, key=key)
        elif self.objective == 'max':
            candidate = max(self.solutions, key=key)
            
        if self.best_solution is None or self.compare_objective_value(candidate, self.best_solution) < 0:
            self.best_solution = np.copy(candidate)
        
        return self.best_solution


    def compare_objective_value(self, s0, s1):
        v0 = self.objective_fct(s0)
        v1 = self.objective_fct(s1)

        if self.objective == 'min':
            return v0 - v1
        elif self.objective == 'max':
            return v1 - v0
        
        
    def argsort_objective(self):
        if self.objective == 'min':
            return np.argsort([self.objective_fct(s) for s in self.solutions]).ravel()
        elif self.objective == 'max':
            return np.argsort([self.objective_fct(s)for s in self.solutions])[::-1].ravel()
    
    
    def evaluation_count_decorator(self, f, x):
        self.evaluation_count += 1
        return f(x)
    
    
    def random_uniform_in_ranges(self):
        rnd = np.zeros(self.d)
        for i in range(self.d):
            rnd[i] = np.random.uniform(self.range_min[i], self.range_max[i])
        return rnd
    
    def clip_to_ranges(self, x):
        for i in range(self.d):
            x[i] = np.clip(x[i], self.range_min[i], self.range_max[i])
        return x
    
    
    def search(self, objective, objective_fct, T, visualize=False):
        
        if not self.constraints_satisfied():
            return (np.nan, np.nan), np.nan
        
        self.objective = objective
        self.evaluation_count = 0
        self.objective_fct = lambda x: self.evaluation_count_decorator(objective_fct, x)
        self.history = np.zeros((T, self.d))
        self.best_solution = self.random_uniform_in_ranges()
        self.initialize()
        
        t_start = process_time()
        

        if visualize:
            self.visualize_search_step()
            
        for t in range(T):
            self.execute_search_step(t)
            self.history[t] = self.get_best_solution() 

            if visualize:
                self.visualize_search_step(t+1)

        t_end = process_time()

        return (self.best_solution, self.objective_fct(self.best_solution)), t_end-t_start


    def plot_history(self):
        plt.plot([self.objective_fct(s) for s in self.history])
        plt.xlabel('iteration')
        plt.ylabel('objective function value')
        plt.show()


    def initialize(self):
        raise NotImplementedError


    def execute_search_step(self, t):
        raise NotImplementedError


    def visualize_search_step(self, t=0):
        if self.d != 2:
            return
        
        range_min = np.max(self.range_min)
        range_max = np.max(self.range_max)
        
        x = np.linspace(range_min, range_max, 100)
        y = np.linspace(range_min, range_max, 100)
        
        X, Y = np.meshgrid(x, y)
        
        XY = np.array((X, Y)).T
        Z = np.zeros(XY.shape[:-1])
        for i in range(Z.shape[0]):
            for j in range(Z.shape[1]):
                Z[i,j] = self.objective_fct(XY[i,j])
        
        fig = plt.figure(figsize=(8, 8))
        ax = fig.add_subplot(111, aspect='equal')
        
        
        ax.set_xlim([range_min, range_max])
        ax.set_ylim([range_min, range_max])       

        ax.contourf(X, Y, Z, 20, cmap='Greys');
        ax.contour(X, Y, Z, 20, colors='black', linestyles='dotted');
        
        ax.scatter(self.solutions.T[0], self.solutions.T[1], marker='.', c='black')
        ax.scatter(self.best_solution[0], self.best_solution[1], marker='X', s=100, c='red')
        
        savepath = f"images/{self.name}/"
        
        if not os.path.isdir(savepath):
            os.makedirs(savepath)
        
        plt.savefig(os.path.join(savepath, f"{self.name}_{t}.png"))
        plt.close()
        
        
    def generate_gif(self, filename=None):
        if not filename:
            filename = self.name
        
        plot_paths = [f"images/{self.name}/"+file for file in os.listdir(f"images/{self.name}")]
        
        with imageio.get_writer(f"{filename}.gif", mode='I') as writer:
            for filepath in plot_paths:
                image = imageio.imread(filepath)
                writer.append_data(image)

class FireflyAlgorithm(BaseSearchAlgorithm):

    def __init__(self, **kwargs):
        super().__init__("firefly", **kwargs)

        self.alpha = self.params['alpha'] # neighbor sphere radius
        self.beta_max = self.params['beta_max'] # maximum attractivneness
        self.gamma = self.params['gamma'] # attractiveness descreasing factor


    def initialize(self):
        self.solutions = np.zeros(shape=(self.n, self.d))
        for i in range(self.n):
            self.solutions[i] = self.random_uniform_in_ranges()
            
            
    def execute_search_step(self, t):
        for i in range(self.n):
            for j in range(self.n):

                if self.light_intensity(i) < self.light_intensity(j):
                    diff_ij = (self.solutions[j] - self.solutions[i])
                    r_ij = np.sqrt(np.sum(np.square(diff_ij)))
                    beta_ij = self.beta_max * np.exp(-self.gamma * r_ij**2)
                    self.solutions[i] += beta_ij * diff_ij + self.alpha * np.random.uniform(-0.5, 0.5, self.d)
                    self.clip_to_ranges(self.solutions[i])


    def light_intensity(self, i):
        if self.objective == 'min':
            return 1 / (1e-16+self.objective_fct(self.solutions[i]))
        elif self.objective == 'max':
            return self.objective_fct(self.solutions[i])

lb = [1.0, 10.0]
ub = [0.0001, 0.1]

d = 2 # dimensionality of solution-space
n = 25 # size of population, related to amount of fireflies
range_min, range_max = lb, ub # solution-space range (in all dimensions)
T = 5 # number of iterations

firefly = FireflyAlgorithm(d=d, n=n, range_min=range_min, range_max=range_max,
                           alpha=1.0, beta_max=1.0, gamma=0.5)

objective = 'min'
objective_fct = fitness_function

solution = firefly.search(objective, objective_fct, T)
print(solution)
print(latency)
firefly.plot_history()